## Section C: Practical Notebook Build

** 1.Create or load the dataset and display the first rows**

In [11]:
import pandas as pd
data = {
    "student_id":["2026CS001","2026CS002","2026IT001","2026IT002","2026CE001","2026CE002","2026CS003","2026IT003"],
    "name":["Aditi","Bhavana","Chaitra","Divya","Esha","Fatima","Gauri","Harshada"],
    "department":["Computer Engineering","Computer Engineering","Information Technology","Information Technology","Civil Engineering",
                  "Civil Engineering","Computer Engineering","Information Technology"],
    "attendance_pct":[92,64,78,55,88,71,96,43],
    "diary_entries":[12,6,9,4,10,8,14,2],
    "tasks_completed":[8,5,7,3,8,6,9,2],
    "assignment_score":[84,58,72,46,79,66,91,35],
    "lab_score":[88,61,76,52,82,69,94,41]
}

df = pd.DataFrame(data)

df.to_csv("week_2_3_exam_student_signals.csv",index=False)

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76
3,2026IT002,Divya,Information Technology,55,4,3,46,52
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82

 **Explanation**

In this step, I created the student dataset and converted it into a DataFrame. Then I saved it as a CSV file and displayed the first five records.

**2.Check data types, missing values, and basic shape**

In [12]:
print("Data Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nShape")
print(df.shape)

Data Types
student_id            str
name                  str
department            str
attendance_pct      int64
diary_entries       int64
tasks_completed     int64
assignment_score    int64
lab_score           int64
dtype: object

Missing Values
student_id          0
name                0
department          0
attendance_pct      0
diary_entries       0
tasks_completed     0
assignment_score    0
lab_score           0
dtype: int64

Shape
(8, 8)

 **Explanation**

In this step, I checked the number of rows and columns, the data types of each column, and whether there are any missing values in the dataset.



**3.Calculate the readiness score using attendance, diary entries, tasks completed, assignment score, and lab score.**

In [13]:
def readiness_score(attendance, diary, tasks, assignment, lab):
    score = (
        attendance * 0.30 +
        diary * 2 +
        tasks * 3 +
        assignment * 0.25 +
        lab * 0.25
    )
    if score > 100:
        score = 100

    return round(score, 2)

df["readiness_score"] = df.apply(lambda x: readiness_score(  x["attendance_pct"], x["diary_entries"],x["tasks_completed"],
                                                             x["assignment_score"],x["lab_score"]), axis=1)

df[["name","readiness_score"]]

       name  readiness_score
0     Aditi           100.00
1   Bhavana            75.95
2   Chaitra            99.40
3     Divya            58.00
4      Esha           100.00
5    Fatima            89.05
6     Gauri           100.00
7  Harshada            41.90

**Explanation**

In this step, I created a function to calculate the readiness score for each student. The score is calculated using attendance, diary entries, tasks completed, assignment score, and lab score. Then I added the readiness score as a new column in the dataset.

**4.Use loops or apply logic to classify each student into Support, Developing, Strong, or Excellent**

In [14]:
performance = []

for score in df["readiness_score"]:
    if score < 45:
        performance.append("Support")
    elif score < 70:
        performance.append("Developing")
    elif score < 90:
        performance.append("Strong")
    else:
        performance.append("Excellent")

df["Performance_Band"] = performance

df[["name","readiness_score","Performance_Band"]]

       name  readiness_score Performance_Band
0     Aditi           100.00        Excellent
1   Bhavana            75.95           Strong
2   Chaitra            99.40        Excellent
3     Divya            58.00       Developing
4      Esha           100.00        Excellent
5    Fatima            89.05           Strong
6     Gauri           100.00        Excellent
7  Harshada            41.90          Support

**Explanation**

In this step, I used a loop to check the readiness score of each student. Based on the score, I classified each student as Support, Developing, Strong, or Excellent. Then I stored the result in a new column called Performance_Band.

**5. Generate at least three analytics outputs: department average, top performer, and students needing support.**

In [15]:
print("Department Average Readiness Score")
print(df.groupby("department")["readiness_score"].mean())

print("\nTop Performer")
top = df.loc[df["readiness_score"].idxmax()]
print(top[["name","department","readiness_score"]])

print("\nStudents Needing Support")
print(df[df["Performance_Band"]=="Support"][["name","department","readiness_score"]])

Department Average Readiness Score
department
Civil Engineering         94.525000
Computer Engineering      91.983333
Information Technology    66.433333
Name: readiness_score, dtype: float64

Top Performer
name                              Aditi
department         Computer Engineering
readiness_score                   100.0
Name: 0, dtype: object

Students Needing Support
       name              department  readiness_score
7  Harshada  Information Technology             41.9

 **Explanation**

In this step, I found the average readiness score for each department. I also identified the top performer and displayed the students who need support based on their performance band.